apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-profiles-pvc
  namespace: profilezee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
