
apiVersion: v1
kind: Secret
metadata:
  name: profilezee-app-secrets
  namespace: profilezee
type: Opaque
stringData:
  JWT_SECRET: your-super-secret-jwt-key-change-in-production
  SMTP_USER: princewillopah.dev@gmail.com
  SMTP_PASSWORD: xxx # Change to your actual SMTP password or use environment variables in production
  AWS_ACCESS_KEY_ID: xxx # Change to your actual AWS credentials
  AWS_SECRET_ACCESS_KEY: xxx # Change to your actual AWS credentials
  AWS_S3_BUCKET: xxx  # Change to your actual S3 bucket name

  USERS_DATABASE_URL: postgresql+asyncpg://admin:secret@postgres-users:5432/users_db
  PROFILES_DATABASE_URL: postgresql+asyncpg://admin:secret@postgres-profiles:5432/profiles_db
  AUTH_DATABASE_URL: jdbc:mysql://mysql-auth:3306/auth_db




