apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
type: Opaque
stringData:
  admin-user: admin
  admin-password: Grafana@1234
  GF_SMTP_USER: xxx # Change to your actual SMTP user or use environment variables in production
  GF_SMTP_PASSWORD: xxx # Change to your actual SMTP password or use environment variables in production
