apiVersion: v1
kind: Secret
metadata:
  name: profilezee-infra-secrets
  namespace: profilezee
type: Opaque
stringData:
# MYSQL_DATABASE: auth_db
  MYSQL_DATABASE: auth_db
  MYSQL_USER: admin
  MYSQL_PASSWORD: secret
  MYSQL_ROOT_PASSWORD: rootsecret
#  POSTGRES_DB: user_db
  USER_POSTGRES_DB: users_db
  USER_POSTGRES_USER: admin
  USER_POSTGRES_PASSWORD: secret
# POSTGRES_DB: profiles_db
  PROFILES_POSTGRES_DB:  profiles_db
  PROFILES_POSTGRES_USER: admin
  PROFILES_POSTGRES_PASSWORD: secret


# REDIS_URL: redis://redis:6379
  REDIS_URL: redis://redis:6379