
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-users-pvc
  namespace: profilezee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard