
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-users
  namespace: profilezee
spec:
  serviceName: postgres-users
  replicas: 1
  selector:
    matchLabels:
      app: postgres-users

  template:
    metadata:
      labels:
        app: postgres-users

    spec:
      containers:
        - name: postgres-users
          image: postgres:15

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: profilezee-infra-secrets
                  key: USER_POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: profilezee-infra-secrets
                  key: USER_POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profilezee-infra-secrets
                  key: USER_POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-users-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB)
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB)
            initialDelaySeconds: 30
            periodSeconds: 10

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: postgres-users-storage
          persistentVolumeClaim:
            claimName: postgres-users-pvc

