apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  namespace: profilezee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: princewillopah2/profilezee-profile-service:latest
          ports:
            - containerPort: 8002

          envFrom:
            - configMapRef:
                name: profilezee-app-config
            - secretRef:
                name: profilezee-app-secrets

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: profilezee-app-secrets
                  key: PROFILES_DATABASE_URL

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 25
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 25
            periodSeconds: 15

