apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  namespace: profilezee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: princewillopah2/profilezee-profile-service:latest
          ports:
            - containerPort: 8002

          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: profilezee-app-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: profilezee-app-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: profilezee-app-secrets
                  key: AWS_S3_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: profilezee-app-config
                  key: AWS_REGION
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: profilezee-infra-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: profilezee-app-secrets
                  key: PROFILES_DATABASE_URL

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 25
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 25
            periodSeconds: 15

