apiVersion: v1
kind: ConfigMap
metadata:
  name: profilezee-app-config
  namespace: profilezee
data:
  AWS_REGION: "us-east-1"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  FROM_EMAIL: "noreply@userapp.com"