apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: profilezee

data:
  default.conf: |
    server {
      listen 80;

      root /usr/share/nginx/html;
      index index.html;

      location / {
          try_files $uri /index.html;
      }

      location /api/users/ {
          proxy_pass http://user-service:8001/;
      }

      location /api/profiles/ {
          proxy_pass http://profile-service:8002/;
      }

      location /api/auth/ {
          proxy_pass http://auth-service:8003/;
      }

      location /api/notifications/ {
          proxy_pass http://notification-service:8004/;
      }
    }