apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: profilezee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          ports:
            - containerPort: 8004

          envFrom:
            - configMapRef:
                name: profilezee-app-config
            - secretRef:
                name: profilezee-app-secrets
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: profilezee-infra-secrets
                  key: KAFKA_BOOTSTRAP_SERVERS
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 25
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 25
            periodSeconds: 15
