apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  namespace: profilezee
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi
  storageClassName: standard