apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: profilezee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: princewillopah2/profilezee-auth-service:latest
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: profilezee-app-config
            - secretRef:
                name: profilezee-app-secrets
          env:
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: profilezee-app-secrets
                  key: AUTH_DATABASE_URL
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: profilezee-infra-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profilezee-infra-secrets
                  key: MYSQL_PASSWORD
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m -XX:+UseContainerSupport"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: profilezee-app-secrets
                  key: JWT_SECRET
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health    # ← was /health
              port: 8003
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health    # ← was /health
              port: 8003
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 10